### ISSUE TITLE
persecutor hitbox is being triggered on damage but no damage occurs on persecutor

### ISSUE THREAD

**Issue by drivver44** [beyond-all-reason/Beyond-All-Reason#1387]
https://bar-rts.com/replays/9bef52636512eaabb2c2f83f1aaebe75

33 min mark deltars makes arm tachyons and they dont damage the cortoast

**Comment by badosu** [comment]
Is this resolved now?

**Comment by drivver44** [comment]
yes and no
the actual cause of the issue is still a thing
the change of the aim point is the bandaide solution
the root cause is not fixed

**Comment by SethDGamre** [comment]
Correct me if I'm wrong and I'll reopen, but the remaining solution appears to need doing engine-side meaning this issue is concluded.
