### ISSUE TITLE
linux nouveau driver broken

### ISSUE THREAD

**Issue by murtagon** [beyond-all-reason/Beyond-All-Reason#1676]
I use the Arch linux open source nouveau Nvidia driver because the Nvidia proprietary driver stopped supporting my nv60 video card. The BAR engine seems to write to system memory instead of video card memory and it  crashes the OS.  BAR is really slow then eventually the system crashes.  The 105 engine works great.  All other video games work normally .

**Comment by badosu** [comment]
Can you share infolog/stacktrace? This might be better addressed at https://github.com/beyond-all-reason/spring

**Comment by hihoman23** [comment]
Is this still an issue?

**Comment by AntlerForce** [comment]
> Is this still an issue?

https://github.com/beyond-all-reason/Beyond-All-Reason/issues/6347#issuecomment-3594619740

As of Nov 2025 Nouveau still crashes, I doubt this is something Recoil can fix.
