### ISSUE TITLE
scenario 'not completed yet'

### ISSUE THREAD

**Issue by nullaegy** [beyond-all-reason/Beyond-All-Reason#2196]
If I complete a scenario, the completion status is not going to be recorded, insted it stays "not completed yet".
I've tried to complete reinstall the game, and removed any app data related.
It seems there is no effect wether I logged in or not.

windows 11 (Version 10.0.22621.2428) 
installed from `Beyond-All-Reason-1.2470.0.exe`
`BAR-24476-f797454 Engine: 105.1.1-1821-gaca6f20105 Chobby: 2640-5aead02`

```
[t=00:01:44.208284][f=-000001] Player nullaegy finished loading and is now ingame
[2023-10-26 17:00:05.032] [info]  [t=00:01:44.236851][f=-000001] Scenario: Spawning loadout instead of regular commanders
...
[2023-10-26 17:04:42.534] [info]  [t=00:06:21.738687][f=0008348] TopHatButcher is defeated
[2023-10-26 17:04:42.543] [info]  [t=00:06:21.747958][f=0008349] winners, nil
[2023-10-26 17:04:42.581] [info]  [t=00:06:21.785469][f=0008349] Fallendellheadstart008, 1, 278.299988, 8389, false
[2023-10-26 17:04:48.047] [info]  [t=00:06:27.251230][f=0008514] <autoquit> Automatically exiting in 12 seconds. Move mouse to postpone the quit for 60 seconds
```

**Comment by nullaegy** [comment]
it's already fixed in recent version :) thank you whoever it was 👍 
`BAR-24519-8856783` Engine: 105.1.1-1821-gaca6f20105 Chobby: 2640-5aead02

**Comment by hohider** [comment]
I'm still having this issue.  The last 4 scenarios I completed are marked as incomplete.  At least one of the 4 was marked complete just after finishing the scenario but later marked incomplete.  I'm running version 105.1.1-2240-gd01542d bar

**Comment by Beherith** [comment]
Did it fix itself after restarting the game?

**Comment by nullaegy** [comment]
Back in the day I made several reinstall, but eventually nothing woked, except the update of the game.
Maybe the solution was the complete reinstall + the update later on, but i cannot confirm this.
