### ISSUE TITLE
Adding a unit that's currently being built to a control group (Autogroup immediate mode: ON) makes its control group number display disappear when it leaves the factory

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#3448]
### Description

If you bind a unit to a group while it's being built, on leaving the factory, the visual display will make it look like it's not in any group. 

![image](https://github.com/user-attachments/assets/11b2f997-b011-43ec-910f-29d6fde1351f)

It gets fixed when you add another unit to the group.

### Expected Behaviour

Visual group number indicator stays.

### Actual Behaviour

Visual group number indicator disappears upon leaving the factory.

### Reproduction steps

Start making a unit (that you assigned to an autogroup at some previous point), add it to another control group. See result after it leaves the factory.

**Comment by TheFutureKnight** [comment]
- `UnitFinished` in the [visible units tracker widget](https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luaui/Widgets/api_unit_tracker_gl4.lua) triggers `VisibleUnitRemoved` closely followed with `VisibleUnitAdded`.
- The [group number widget](https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luaui/Widgets/gui_unit_group_number.lua#L123-L125) removes uniform in `VisibleUnitRemoved` but does not add it in `VisibleUnitAdded`
- The unit is "fixed" when another is built or when the group changes because it triggers GroupChanged callin, sanitizing state.

Explained by @badosu

**Comment by badosu** [comment]
Fixed as soon as https://github.com/beyond-all-reason/Beyond-All-Reason/pull/4589 is merged

**Comment by TheFutureKnight** [comment]
> Fixed as soon as https://github.com/beyond-all-reason/Beyond-All-Reason/pull/4589 is merged

Think you meant #4457? This only fixes the immediate mode but doesn't fix the visual number, this issue talks about the visual

**Comment by badosu** [comment]
> > Fixed as soon as https://github.com/beyond-all-reason/Beyond-All-Reason/pull/4589 is merged
> 
> Think you meant #4457? This only fixes the immediate mode not assigning but doesn't fix the visual number, this issue talks about the visual

You are absolutely correct. Thank you
